-- Preserve changing bookmaker quotes for pre-kickoff line movement and CLV.
BEGIN;

CREATE TABLE IF NOT EXISTS public.odds_quote_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    bookmaker TEXT NOT NULL,
    odds JSONB NOT NULL,
    source_updated_at TIMESTAMPTZ,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_notification_reference BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_odds_quote_history_match_time
    ON public.odds_quote_history(match_id, captured_at DESC);
GRANT SELECT, INSERT ON public.odds_quote_history TO service_role;
REVOKE ALL ON public.odds_quote_history FROM anon, authenticated;
GRANT SELECT ON public.odds_quote_history TO anon;
ALTER TABLE public.odds_quote_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public_read_odds_quote_history" ON public.odds_quote_history;
CREATE POLICY "public_read_odds_quote_history" ON public.odds_quote_history FOR SELECT TO anon USING (true);

COMMIT;
