-- Preserve each availability refresh for causal future model training.
BEGIN;

CREATE TABLE IF NOT EXISTS public.team_availability_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INTEGER NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
    refreshed_at TIMESTAMPTZ NOT NULL,
    available_count INTEGER NOT NULL CHECK (available_count >= 0),
    UNIQUE (team_id, refreshed_at)
);

CREATE INDEX IF NOT EXISTS idx_availability_history_team_time
    ON public.team_availability_history(team_id, refreshed_at DESC);
GRANT SELECT, INSERT ON public.team_availability_history TO service_role;
REVOKE ALL ON public.team_availability_history FROM anon, authenticated;

COMMIT;
