-- Persist bounded backend telemetry for quota monitoring and operational alerts.
BEGIN;

CREATE TABLE IF NOT EXISTS public.operational_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'error')),
    component TEXT NOT NULL,
    event_type TEXT NOT NULL,
    message TEXT NOT NULL,
    context JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE INDEX IF NOT EXISTS idx_operational_events_occurred_at
    ON public.operational_events (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_operational_events_attention
    ON public.operational_events (severity, occurred_at DESC)
    WHERE severity IN ('warning', 'error');

REVOKE ALL ON TABLE public.operational_events FROM anon, authenticated;
GRANT SELECT, INSERT ON TABLE public.operational_events TO service_role;
NOTIFY pgrst, 'reload schema';

COMMIT;
