-- Decision journal for the authenticated single user.
begin;

create table if not exists public.personal_match_decisions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    match_id bigint not null references public.matches(id) on delete cascade,
    prediction_snapshot_id bigint references public.predictions(id) on delete set null,
    decision text not null check (decision in ('played', 'passed', 'ignored')),
    selected_market text,
    selected_odds numeric,
    model_probability numeric,
    model_threshold numeric,
    note text not null default '',
    match_result text,
    was_correct boolean,
    result_settled_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.personal_match_decisions enable row level security;

drop policy if exists personal_match_decisions_select on public.personal_match_decisions;
create policy personal_match_decisions_select
    on public.personal_match_decisions for select using (auth.uid() = user_id);

drop policy if exists personal_match_decisions_insert on public.personal_match_decisions;
create policy personal_match_decisions_insert
    on public.personal_match_decisions for insert with check (auth.uid() = user_id);

drop policy if exists personal_match_decisions_update on public.personal_match_decisions;
create policy personal_match_decisions_update
    on public.personal_match_decisions for update
    using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists personal_match_decisions_user_created_idx
    on public.personal_match_decisions (user_id, created_at desc);
create index if not exists personal_match_decisions_match_idx
    on public.personal_match_decisions (user_id, match_id, created_at desc);

commit;
