-- Normalized Nesine market selections. Raw odds remain in odds_quote_history
-- for backwards compatibility; this table makes every market queryable.
BEGIN;

CREATE TABLE IF NOT EXISTS public.nesine_market_quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    market_code TEXT NOT NULL,
    market_name TEXT NOT NULL,
    selection_code TEXT NOT NULL,
    selection_name TEXT NOT NULL,
    odd NUMERIC(8,3) NOT NULL CHECK (odd > 1),
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_url TEXT,
    UNIQUE(match_id, market_code, selection_code, captured_at)
);

CREATE INDEX IF NOT EXISTS idx_nesine_market_quotes_match_time
    ON public.nesine_market_quotes(match_id, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_nesine_market_quotes_market
    ON public.nesine_market_quotes(market_code, captured_at DESC);

GRANT SELECT, INSERT ON public.nesine_market_quotes TO service_role;
REVOKE ALL ON public.nesine_market_quotes FROM anon, authenticated;
GRANT SELECT ON public.nesine_market_quotes TO anon;
ALTER TABLE public.nesine_market_quotes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public_read_nesine_market_quotes" ON public.nesine_market_quotes;
CREATE POLICY "public_read_nesine_market_quotes"
    ON public.nesine_market_quotes FOR SELECT TO anon USING (true);

COMMIT;
