-- Deduplicate automatic pre-match messages across recurring workflow runs.
BEGIN;

CREATE TABLE IF NOT EXISTS public.notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    notification_type TEXT NOT NULL,
    model_version TEXT,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (match_id, notification_type)
);

CREATE INDEX IF NOT EXISTS idx_notification_log_sent_at
ON public.notification_log(sent_at DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.notification_log TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

COMMIT;
