BEGIN;

CREATE TABLE IF NOT EXISTS leagues (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    country TEXT,
    season INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS teams (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    league_id INTEGER REFERENCES leagues(id) ON DELETE SET NULL,
    logo_url TEXT
);

CREATE TABLE IF NOT EXISTS matches (
    id INTEGER PRIMARY KEY,
    league_id INTEGER REFERENCES leagues(id) ON DELETE SET NULL,
    home_team_id INTEGER REFERENCES teams(id) ON DELETE SET NULL,
    away_team_id INTEGER REFERENCES teams(id) ON DELETE SET NULL,
    match_date TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL,
    home_score INTEGER CHECK (home_score IS NULL OR home_score >= 0),
    away_score INTEGER CHECK (away_score IS NULL OR away_score >= 0),
    home_xg NUMERIC CHECK (home_xg IS NULL OR home_xg >= 0),
    away_xg NUMERIC CHECK (away_xg IS NULL OR away_xg >= 0),
    home_xa NUMERIC CHECK (home_xa IS NULL OR home_xa >= 0),
    away_xa NUMERIC CHECK (away_xa IS NULL OR away_xa >= 0),
    expected_metrics_checked_at TIMESTAMPTZ,
    CONSTRAINT different_teams CHECK (home_team_id IS NULL OR away_team_id IS NULL OR home_team_id <> away_team_id)
);

CREATE TABLE IF NOT EXISTS match_stats (
    match_id INTEGER REFERENCES matches(id) ON DELETE CASCADE,
    team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
    shots_total INTEGER CHECK (shots_total IS NULL OR shots_total >= 0),
    shots_on_target INTEGER CHECK (shots_on_target IS NULL OR shots_on_target >= 0),
    possession NUMERIC CHECK (possession IS NULL OR possession BETWEEN 0 AND 100),
    corners INTEGER CHECK (corners IS NULL OR corners >= 0),
    fouls INTEGER CHECK (fouls IS NULL OR fouls >= 0),
    yellow_cards INTEGER CHECK (yellow_cards IS NULL OR yellow_cards >= 0),
    red_cards INTEGER CHECK (red_cards IS NULL OR red_cards >= 0),
    PRIMARY KEY (match_id, team_id)
);

CREATE TABLE IF NOT EXISTS team_form (
    team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
    calculated_at TIMESTAMPTZ NOT NULL,
    elo_rating NUMERIC NOT NULL,
    avg_goals_scored_last5 NUMERIC CHECK (avg_goals_scored_last5 IS NULL OR avg_goals_scored_last5 >= 0),
    avg_goals_conceded_last5 NUMERIC CHECK (avg_goals_conceded_last5 IS NULL OR avg_goals_conceded_last5 >= 0),
    win_rate_last5 NUMERIC CHECK (win_rate_last5 IS NULL OR win_rate_last5 BETWEEN 0 AND 1),
    home_away_split JSONB NOT NULL DEFAULT '{}'::JSONB,
    PRIMARY KEY (team_id, calculated_at)
);

CREATE TABLE IF NOT EXISTS player_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
    player_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('injured', 'suspended', 'doubtful')),
    expected_return DATE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Records refresh completion so an empty injury list is never mistaken for stale data.
CREATE TABLE IF NOT EXISTS team_availability_status (
    team_id INTEGER PRIMARY KEY REFERENCES teams(id) ON DELETE CASCADE,
    refreshed_at TIMESTAMPTZ NOT NULL,
    available_count INTEGER NOT NULL DEFAULT 0 CHECK (available_count >= 0)
);

CREATE TABLE IF NOT EXISTS fixture_lineups (
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    formation TEXT,
    coach_name TEXT,
    starters JSONB NOT NULL DEFAULT '[]'::JSONB,
    substitutes JSONB NOT NULL DEFAULT '[]'::JSONB,
    confirmed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (match_id, team_id)
);

CREATE TABLE IF NOT EXISTS predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    model_version TEXT NOT NULL,
    prob_home_win NUMERIC NOT NULL CHECK (prob_home_win BETWEEN 0 AND 1),
    prob_draw NUMERIC NOT NULL CHECK (prob_draw BETWEEN 0 AND 1),
    prob_away_win NUMERIC NOT NULL CHECK (prob_away_win BETWEEN 0 AND 1),
    prob_over_2_5 NUMERIC CHECK (prob_over_2_5 IS NULL OR prob_over_2_5 BETWEEN 0 AND 1),
    prob_btts NUMERIC CHECK (prob_btts IS NULL OR prob_btts BETWEEN 0 AND 1),
    predicted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT valid_1x2_probability_sum CHECK (ABS((prob_home_win + prob_draw + prob_away_win) - 1) <= 0.001),
    UNIQUE (match_id, model_version)
);

-- The exact production output used for the pre-match alert. This is append-only:
-- later model refreshes must never rewrite what was shown to a user.
CREATE TABLE IF NOT EXISTS prediction_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_prediction_id BIGINT NOT NULL REFERENCES predictions(id) ON DELETE RESTRICT,
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    snapshot_type TEXT NOT NULL CHECK (snapshot_type IN ('pre_match_60m')),
    model_version TEXT NOT NULL,
    prob_home_win NUMERIC NOT NULL CHECK (prob_home_win BETWEEN 0 AND 1),
    prob_draw NUMERIC NOT NULL CHECK (prob_draw BETWEEN 0 AND 1),
    prob_away_win NUMERIC NOT NULL CHECK (prob_away_win BETWEEN 0 AND 1),
    prob_over_2_5 NUMERIC CHECK (prob_over_2_5 IS NULL OR prob_over_2_5 BETWEEN 0 AND 1),
    prob_btts NUMERIC CHECK (prob_btts IS NULL OR prob_btts BETWEEN 0 AND 1),
    source_predicted_at TIMESTAMPTZ NOT NULL,
    context JSONB NOT NULL DEFAULT '{}'::JSONB,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT snapshot_valid_1x2_probability_sum CHECK (ABS((prob_home_win + prob_draw + prob_away_win) - 1) <= 0.001),
    UNIQUE (match_id, snapshot_type)
);

CREATE TABLE IF NOT EXISTS prediction_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id BIGINT NOT NULL UNIQUE REFERENCES predictions(id) ON DELETE CASCADE,
    snapshot_id BIGINT UNIQUE REFERENCES prediction_snapshots(id) ON DELETE RESTRICT,
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    actual_result TEXT NOT NULL CHECK (actual_result IN ('home_win', 'draw', 'away_win')),
    was_correct BOOLEAN NOT NULL,
    brier_score NUMERIC NOT NULL CHECK (brier_score BETWEEN 0 AND 2),
    log_loss NUMERIC CHECK (log_loss IS NULL OR log_loss >= 0),
    over_2_5_actual BOOLEAN,
    over_2_5_was_correct BOOLEAN,
    over_2_5_brier_score NUMERIC CHECK (over_2_5_brier_score IS NULL OR over_2_5_brier_score BETWEEN 0 AND 1),
    btts_actual BOOLEAN,
    btts_was_correct BOOLEAN,
    btts_brier_score NUMERIC CHECK (btts_brier_score IS NULL OR btts_brier_score BETWEEN 0 AND 1),
    evaluated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    notification_type TEXT NOT NULL,
    model_version TEXT,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (match_id, notification_type)
);

CREATE TABLE IF NOT EXISTS result_notification_queue (
    prediction_id BIGINT PRIMARY KEY REFERENCES predictions(id) ON DELETE CASCADE,
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_error TEXT
);

CREATE TABLE IF NOT EXISTS operational_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'error')),
    component TEXT NOT NULL,
    event_type TEXT NOT NULL,
    message TEXT NOT NULL,
    context JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE TABLE IF NOT EXISTS bookmaker_odds_snapshots (
    prediction_id BIGINT PRIMARY KEY REFERENCES predictions(id) ON DELETE CASCADE,
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    bookmaker TEXT NOT NULL,
    source_updated_at TIMESTAMPTZ,
    odds JSONB NOT NULL,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS odds_quote_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    bookmaker TEXT NOT NULL,
    odds JSONB NOT NULL,
    source_updated_at TIMESTAMPTZ,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_notification_reference BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS model_candidates (
    model_version TEXT PRIMARY KEY,
    status TEXT NOT NULL CHECK (status IN ('shadow', 'promoted', 'rejected')) DEFAULT 'shadow',
    offline_metrics JSONB NOT NULL,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    promoted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS shadow_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_version TEXT NOT NULL REFERENCES model_candidates(model_version) ON DELETE CASCADE,
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    prob_home_win NUMERIC NOT NULL CHECK (prob_home_win BETWEEN 0 AND 1),
    prob_draw NUMERIC NOT NULL CHECK (prob_draw BETWEEN 0 AND 1),
    prob_away_win NUMERIC NOT NULL CHECK (prob_away_win BETWEEN 0 AND 1),
    prob_over_2_5 NUMERIC CHECK (prob_over_2_5 IS NULL OR prob_over_2_5 BETWEEN 0 AND 1),
    prob_btts NUMERIC CHECK (prob_btts IS NULL OR prob_btts BETWEEN 0 AND 1),
    predicted_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT shadow_valid_1x2_probability_sum CHECK (ABS((prob_home_win + prob_draw + prob_away_win) - 1) <= 0.001),
    UNIQUE (model_version, match_id)
);

CREATE TABLE IF NOT EXISTS shadow_prediction_performance (
    shadow_prediction_id BIGINT PRIMARY KEY REFERENCES shadow_predictions(id) ON DELETE CASCADE,
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    was_correct BOOLEAN NOT NULL,
    brier_score NUMERIC NOT NULL CHECK (brier_score BETWEEN 0 AND 2),
    over_2_5_was_correct BOOLEAN,
    over_2_5_brier_score NUMERIC CHECK (over_2_5_brier_score IS NULL OR over_2_5_brier_score BETWEEN 0 AND 1),
    btts_was_correct BOOLEAN,
    btts_brier_score NUMERIC CHECK (btts_brier_score IS NULL OR btts_brier_score BETWEEN 0 AND 1),
    evaluated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_matches_date ON matches(match_date);
CREATE INDEX IF NOT EXISTS idx_matches_league_date ON matches(league_id, match_date);
CREATE INDEX IF NOT EXISTS idx_predictions_match ON predictions(match_id);
CREATE INDEX IF NOT EXISTS idx_prediction_snapshots_match ON prediction_snapshots(match_id, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_team_form_latest ON team_form(team_id, calculated_at DESC);
CREATE INDEX IF NOT EXISTS idx_player_availability_team ON player_availability(team_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_fixture_lineups_match ON fixture_lineups(match_id);
CREATE INDEX IF NOT EXISTS idx_notification_log_sent_at ON notification_log(sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_result_notification_queue_pending ON result_notification_queue(next_attempt_at)
WHERE sent_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_operational_events_occurred_at ON operational_events(occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_operational_events_attention ON operational_events(severity, occurred_at DESC)
WHERE severity IN ('warning', 'error');
CREATE INDEX IF NOT EXISTS idx_bookmaker_odds_snapshots_match ON bookmaker_odds_snapshots(match_id);
CREATE INDEX IF NOT EXISTS idx_odds_quote_history_match_time ON odds_quote_history(match_id, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_shadow_predictions_match ON shadow_predictions(match_id);
CREATE INDEX IF NOT EXISTS idx_shadow_performance_match ON shadow_prediction_performance(match_id);

-- Tables remain unavailable to anon/authenticated clients; scheduled backend
-- jobs authenticate with the privileged service_role key.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
    leagues,
    teams,
    matches,
    match_stats,
    team_form,
    player_availability,
    team_availability_status,
    fixture_lineups,
    predictions,
    prediction_snapshots,
    prediction_performance,
    notification_log,
    result_notification_queue,
    operational_events,
    bookmaker_odds_snapshots
    ,odds_quote_history
    ,model_candidates,
    shadow_predictions,
    shadow_prediction_performance
TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

COMMIT;
